version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword1234
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    hostname: mssql
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

networks:
  app-network: